# Generated by Django 6.0.7 on 2026-07-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('service_type', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='provider/profile/')),
                ('aadhaar_front', models.ImageField(blank=True, null=True, upload_to='provider/kyc/aadhaar/')),
                ('aadhaar_back', models.ImageField(blank=True, null=True, upload_to='provider/kyc/aadhaar/')),
                ('pan_card', models.ImageField(blank=True, null=True, upload_to='provider/kyc/pan/')),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
