# Generated by Django 6.0.7 on 2026-07-24 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Provider', '0001_initial'),
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='service_type',
        ),
        migrations.AddField(
            model_name='provider',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='Service.service'),
        ),
    ]
