# Generated by Django 6.0.7 on 2026-08-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Provider', '0002_remove_provider_service_type_provider_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='completed_jobs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provider',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2),
        ),
    ]
