# Generated by Django 6.0.7 on 2026-08-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Provider', '0003_provider_completed_jobs_provider_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
