# Generated by Django 6.0.7 on 2026-08-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Provider', '0004_provider_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
