# Generated by Django 6.0.7 on 2026-08-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Provider', '0005_provider_google_id_alter_provider_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
