# Generated by Django 6.0.7 on 2026-08-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Provider', '0006_alter_provider_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
