# Generated by Django 6.0.7 on 2026-08-03 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0001_initial'),
        ('Provider', '0002_remove_provider_service_type_provider_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_leads', to='Provider.provider'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('assigned', 'Assigned')], default='pending', max_length=20),
        ),
    ]
