# Generated by Django 6.0.7 on 2026-08-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0002_lead_payment_status_lead_provider_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
